### ISSUE TITLE
placename search to look at nominatim rather than geonames

### ISSUE THREAD

**Issue by metazool** [OSMBuildings/website#1]
hello, i'm somewhat belatedly raising this issue to do with over-optimistic place-name search in a more appropriate forum than Twitter.

The existing problem is this: the place-name search in the top left jumps straight to the top hit rather than offering a drop-down. Now, if you're fairly certain you want the top hit, that's not a bad idea, because drop-downs can be crappy and not very accessible.

But currently, the osmbuildings website is using the geonames API for place-name search; it doesn't have the coverage that OSM's nominatim place search engine does, nor is it so optimised for successful over-optimistic searches of OSM data.

What i'm proposing is to take on the small piece of work extending js/Search.js to use the nominatim API rather than the geonames API.  I noticed you're using explicit language support in geonames, i'm not sure that applies so well to nominatim. Plus, nominatim has lots of built-in optimisation for the osm model, so more significant places will pop up first. 

Here's an example of a nominatim search in json format which should replace the current search API call pretty well: http://nominatim.openstreetmap.org/search?q=newington&format=json 

hth, ttyl 

- Jo

**Comment by kekscom** [comment]
Hi Jo, nominatim is an improvement and a dropdown is definitely missing as well.
Replacing the API is a simple step. Changing the behavior + new UI for multiple results is a bit more complex.
However, I appreciate a contribution.

**Comment by metazool** [comment]
Okay i've made the simplest possible changes in Search.js / _header.php to switch to nominatim on a branch locally. 

I've never done a PR on github before, i'm used to using gitlab at work, i don't seem to be able to create a branch in your repository as per https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/#creating-a-branch to send a  PR to. 

How would you prefer to get contributions, would you for example create a placename-search branch for me to work on? 

Sorry, putting up with my thrashing may be more effort than reward to you. I'm not mad keen on dropdowns myself, though i understand other people have come to expect them ;) 
h

**Comment by kekscom** [comment]
Hi Jo, it's perfectly fine with a 'placename-search' branch. I just created it.
Hopefully you can apply your changes to that. There should be no restrictions.

Just push it. We can discuss the changes afterwards. :-)

**Comment by kekscom** [comment]
Guess it's save to close :-)
